export type LapicDigest = string
export type LapicProblemId = string
export type LapicProblemDigest = string
export type LapicStateId = string
export type LapicRegionId = string
export type LapicBlockId = string
export type LapicRelaxId = string
export type LapicArithmeticPolicyId = string
export type LapicEngineVersion = string
export type LapicLogicalTimestamp = string
export type LapicContentHash = string
export type LapicCanonicalByteDigest = string
export type LapicSlotId = string
export type LapicFrameId = string
export type LapicCandidateId = string
export type LapicDomainId = string
export type LapicObjectiveId = string
export type LapicConstraintId = string
export type LapicActorId = string
export type LapicResourceId = string
export type LapicCapabilityId = string
export type LapicCounterId = string
export type LapicMetadataKey = string
export type LapicDigestSet = readonly LapicDigest[]
export type LapicDeterministicOrderingRelation = -1 | 0 | 1
